// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: tendermint/rpc/grpc/types.proto

package grpc

import (
	abci "github.com/consideritdone/landslidevm/proto/tendermint/abci"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestPing) Reset() {
	*x = RequestPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPing) ProtoMessage() {}

func (x *RequestPing) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPing.ProtoReflect.Descriptor instead.
func (*RequestPing) Descriptor() ([]byte, []int) {
	return file_tendermint_rpc_grpc_types_proto_rawDescGZIP(), []int{0}
}

type RequestBroadcastTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *RequestBroadcastTx) Reset() {
	*x = RequestBroadcastTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBroadcastTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBroadcastTx) ProtoMessage() {}

func (x *RequestBroadcastTx) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBroadcastTx.ProtoReflect.Descriptor instead.
func (*RequestBroadcastTx) Descriptor() ([]byte, []int) {
	return file_tendermint_rpc_grpc_types_proto_rawDescGZIP(), []int{1}
}

func (x *RequestBroadcastTx) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

type ResponsePing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResponsePing) Reset() {
	*x = ResponsePing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePing) ProtoMessage() {}

func (x *ResponsePing) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePing.ProtoReflect.Descriptor instead.
func (*ResponsePing) Descriptor() ([]byte, []int) {
	return file_tendermint_rpc_grpc_types_proto_rawDescGZIP(), []int{2}
}

type ResponseBroadcastTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckTx  *abci.ResponseCheckTx `protobuf:"bytes,1,opt,name=check_tx,json=checkTx,proto3" json:"check_tx,omitempty"`
	TxResult *abci.ExecTxResult    `protobuf:"bytes,2,opt,name=tx_result,json=txResult,proto3" json:"tx_result,omitempty"`
}

func (x *ResponseBroadcastTx) Reset() {
	*x = ResponseBroadcastTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBroadcastTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBroadcastTx) ProtoMessage() {}

func (x *ResponseBroadcastTx) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBroadcastTx.ProtoReflect.Descriptor instead.
func (*ResponseBroadcastTx) Descriptor() ([]byte, []int) {
	return file_tendermint_rpc_grpc_types_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseBroadcastTx) GetCheckTx() *abci.ResponseCheckTx {
	if x != nil {
		return x.CheckTx
	}
	return nil
}

func (x *ResponseBroadcastTx) GetTxResult() *abci.ExecTxResult {
	if x != nil {
		return x.TxResult
	}
	return nil
}

var File_tendermint_rpc_grpc_types_proto protoreflect.FileDescriptor

var file_tendermint_rpc_grpc_types_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2f, 0x72, 0x70, 0x63,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x74, 0x2f, 0x61, 0x62, 0x63, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x69,
	0x6e, 0x67, 0x22, 0x24, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x8e, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x78,
	0x12, 0x3b, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2e,
	0x61, 0x62, 0x63, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x54, 0x78, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x12, 0x3a, 0x0a,
	0x09, 0x74, 0x78, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x62,
	0x63, 0x69, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x54, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x08, 0x74, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xbd, 0x01, 0x0a, 0x0c, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x41, 0x50, 0x49, 0x12, 0x4b, 0x0a, 0x04, 0x50, 0x69,
	0x6e, 0x67, 0x12, 0x20, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x69, 0x6e, 0x67, 0x1a, 0x21, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x60, 0x0a, 0x0b, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x54, 0x78, 0x12, 0x27, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x78, 0x1a,
	0x28, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x78, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72,
	0x69, 0x74, 0x64, 0x6f, 0x6e, 0x65, 0x2f, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x6c, 0x69, 0x64, 0x65,
	0x76, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tendermint_rpc_grpc_types_proto_rawDescOnce sync.Once
	file_tendermint_rpc_grpc_types_proto_rawDescData = file_tendermint_rpc_grpc_types_proto_rawDesc
)

func file_tendermint_rpc_grpc_types_proto_rawDescGZIP() []byte {
	file_tendermint_rpc_grpc_types_proto_rawDescOnce.Do(func() {
		file_tendermint_rpc_grpc_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_tendermint_rpc_grpc_types_proto_rawDescData)
	})
	return file_tendermint_rpc_grpc_types_proto_rawDescData
}

var file_tendermint_rpc_grpc_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tendermint_rpc_grpc_types_proto_goTypes = []interface{}{
	(*RequestPing)(nil),          // 0: tendermint.rpc.grpc.RequestPing
	(*RequestBroadcastTx)(nil),   // 1: tendermint.rpc.grpc.RequestBroadcastTx
	(*ResponsePing)(nil),         // 2: tendermint.rpc.grpc.ResponsePing
	(*ResponseBroadcastTx)(nil),  // 3: tendermint.rpc.grpc.ResponseBroadcastTx
	(*abci.ResponseCheckTx)(nil), // 4: tendermint.abci.ResponseCheckTx
	(*abci.ExecTxResult)(nil),    // 5: tendermint.abci.ExecTxResult
}
var file_tendermint_rpc_grpc_types_proto_depIdxs = []int32{
	4, // 0: tendermint.rpc.grpc.ResponseBroadcastTx.check_tx:type_name -> tendermint.abci.ResponseCheckTx
	5, // 1: tendermint.rpc.grpc.ResponseBroadcastTx.tx_result:type_name -> tendermint.abci.ExecTxResult
	0, // 2: tendermint.rpc.grpc.BroadcastAPI.Ping:input_type -> tendermint.rpc.grpc.RequestPing
	1, // 3: tendermint.rpc.grpc.BroadcastAPI.BroadcastTx:input_type -> tendermint.rpc.grpc.RequestBroadcastTx
	2, // 4: tendermint.rpc.grpc.BroadcastAPI.Ping:output_type -> tendermint.rpc.grpc.ResponsePing
	3, // 5: tendermint.rpc.grpc.BroadcastAPI.BroadcastTx:output_type -> tendermint.rpc.grpc.ResponseBroadcastTx
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tendermint_rpc_grpc_types_proto_init() }
func file_tendermint_rpc_grpc_types_proto_init() {
	if File_tendermint_rpc_grpc_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tendermint_rpc_grpc_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tendermint_rpc_grpc_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBroadcastTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tendermint_rpc_grpc_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tendermint_rpc_grpc_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseBroadcastTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tendermint_rpc_grpc_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tendermint_rpc_grpc_types_proto_goTypes,
		DependencyIndexes: file_tendermint_rpc_grpc_types_proto_depIdxs,
		MessageInfos:      file_tendermint_rpc_grpc_types_proto_msgTypes,
	}.Build()
	File_tendermint_rpc_grpc_types_proto = out.File
	file_tendermint_rpc_grpc_types_proto_rawDesc = nil
	file_tendermint_rpc_grpc_types_proto_goTypes = nil
	file_tendermint_rpc_grpc_types_proto_depIdxs = nil
}
